spring:
  server:
    port: ${SERVER_PORT:8080}
  application:
    name: ${APPLICATION_NAME:materials}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    show-sql: ${SHOW_SQL:true}
    open-in-view: ${OPEN_IN_VIEW:false}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: ${LIQUIBASE_CHANGELOG:classpath:/db/changelog/db.changelog-master.yaml}
  cache:
    type: ${CACHE_TYPE:simple}
    cache-names: ${CACHE_NAMES:reservations,reservationFilters}
    simple:
      cache-names: ${CACHE_NAMES:reservations,reservationFilters}
  management:
    endpoints:
      web:
        exposure:
          include: ${MANAGEMENT_ENDPOINTS_INCLUDE:health,info,caches}
    endpoint:
      health:
        show-details: ${HEALTH_SHOW_DETAILS:always}
      caches:
        enabled: ${CACHES_ENABLED:true}
  security:
    token:
      secret: ${SECURITY_TOKEN_SECRET:MySecretTokenKey}