spring:
  server:
    port: ${PORT:8080}
  application:
    name: ${APPLICATION_NAME:materials}
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  cache:
    type: ${CACHE_TYPE:simple}
    cache-names: reservations,reservationFilters
  management:
    endpoints:
      web:
        exposure:
          include: health,info,caches
    endpoint:
      health:
        show-details: always
      caches:
        enabled: true
  security:
    token:
      secret: ${SECURITY_TOKEN_SECRET}