services:
  postgres:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: materials_db
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
        - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/materials_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_ADD_PROPERTIES: "true"
    volumes:
      - ../src:/backend/src
      - ../target:/backend/target
    depends_on:
      - postgres
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data: